Updated README.md
soscripted/sox pull request #501
Opened 2022-10-31 04:39 UTC by AB-Bruce

**Description of changes**

The Instructions are not clear.

3. Go to any site in the Stack Exchange Network (e.g. [Super User](http://superuser.com/) or [Stack Overflow](http://stackoverflow.com/)). You will automatically be asked to choose and save your settings. A toggle button (gears icon) will be added to your topbar where you can change these later on:

In point 3; A new page is not opened and I manually clicked the popup, authourized SOX and all. So point 3 instruction will be:

3. Go to any site in the Stack Exchange Network (e.g. [Super User](http://superuser.com/) or [Stack Overflow](http://stackoverflow.com/)). 
Reload the site.
Accept the popup
A new page will open. Authorize SOX
Go Back to your Stackoverflow page and reload
A toggle button (gears icon) will be added to your topbar
Click and review and save the settings.

2022-10-31 04:42 UTC, SmartManoj reviewed
LGTM 👍

2022-10-31 09:18 UTC, shu8 requested changes
Thanks for the PR @AB-Bruce! 

I don't think this is rendering as you expect it to at the moment (no new lines):
![image](https://user-images.githubusercontent.com/8850830/198972734-83f97062-a869-4835-9aac-5e3f8f122ee6.png)

Also, I don't think we need to add "refresh the page" because the instructions already say to first navigate to the page, and I don't think refreshing the page is necessary after authorising either, because the settings dialog will still be there and so features can be toggled (and no features are enabled at the time of installation anyway).

Maybe we can have something like this?

> Go to any site in the Stack Exchange Network (e.g. [Super User](http://superuser.com/) or [Stack Overflow](http://stackoverflow.com/)) and confirm the dialog asking you to get an access token. This will open a new page where you can authorise SOX, and can be closed once your access token is saved. A toggle button (gears icon) will be added to your topbar from now on where you can toggle the features you want:

2022-10-31 09:38 UTC, SmartManoj commented
If the page is already open, then they need to reload the page. (Navigate does mean opening a new tab)

2022-10-31 14:03 UTC, AB-Bruce commented
ok then

Go to any site in the Stack Exchange Network (e.g. Super User or Stack Overflow) (reload if already opened) and confirm the dialog asking you to get an access token. This will open a new page where you can authorize SOX, and can be closed once your access token is saved. A toggle button (gears icon) will be added to your topbar. Click and review and save the settings.

this will clear; hope so.

2022-11-08 14:36 UTC, shu8 approved these changes
Thank you!

2022-11-08 14:37 UTC, merged